Mappings:
  RegionMap:
    us-east-1: # virginia
      AMI: ami-0ed9277fb7eb570c9
    us-east-2: # ohio
      AMI: ami-002068ed284fb165b

Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [RegionMap, !Ref AWS::Region, AMI]
        # Fn::FindInMap: 
        #   - RegionMap
        #   - !Ref AWS::Region
        #   - AMI
      SecurityGroups:
        - !Ref MySecurityGroup      
      Tags:
        - Key: "Name"
          Value: !Join ["", ["EC2 Instance for ", !Ref AWS::Region]]
          # Value: !Join 
          #   - ""
          #   - - "EC2 Instance for "
          #     - !Ref AWS::Region
              
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Enable SSH access via port 22"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

