Parameters:
  NameOfService:
    Description: "The name of the service this stack is to be used for." 
    Type: String
  KeyName:
    Description: "The name of an existing EC2 KeyPair to enable SSH access into the server." 
    Type: AWS::EC2::KeyPair::KeyName
  InstanceTypeParameter:
    Type: String
    Description: "EC2 Instance Type"
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large

Mappings:
  RegionMap:
    us-east-1: # virginia
      AMI: ami-0ed9277fb7eb570c9
    us-east-2: # ohio
      AMI: ami-002068ed284fb165b

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      # InstanceType: t2.micro
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !FindInMap [RegionMap, !Ref AWS::Region, AMI]
        # Fn::FindInMap: 
        #   - RegionMap
        #   - !Ref AWS::Region
        #   - AMI
      SecurityGroups:
        - !Ref MySecurityGroup      
      Tags:
        - Key: "Name"
          Value: !Ref NameOfService
          # Value: !Join ["", ["EC2 Instance for ", !Ref AWS::Region]]
          # Value: !Join 
          #   - ""
          #   - - "EC2 Instance for "
          #     - !Ref AWS::Region
      KeyName: !Ref KeyName
              
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Enable SSH access via port 22"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

Outputs:
  ServerDNS:
    Value: !GetAtt EC2Instance.PublicDnsName
    # Value: !GetAtt
    #   - EC2Instance
    #   - PublicDnsName
  ServerAZ:
    Value: !GetAtt EC2Instance.AvailabilityZone
  ServerPrivateIP:
    Value: !GetAtt EC2Instance.PrivateIp
  ServerPublicIP:
    Value: !GetAtt EC2Instance.PublicIp        