apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"melonvote-front","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"melonvote-front"}},"template":{"metadata":{"labels":{"app":"melonvote-front"}},"spec":{"containers":[{"env":[{"name":"REDIS","value":"redis-back"}],"image":"microsoft/azure-vote-front:v1","name":"melonvote-front","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"250m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}],"nodeSelector":{"beta.kubernetes.io/os":"linux"}}}}}
  creationTimestamp: "2022-02-04T23:07:12Z"
  generation: 1
  name: melonvote-front
  namespace: default
  resourceVersion: "1335067"
  uid: 95404ff9-c500-4a64-b1c5-edfe63ae8d32
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: melonvote-front
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: melonvote-front
    spec:
      containers:
      - env:
        - name: REDIS
          value: redis-back
        image: microsoft/azure-vote-front:v1
        imagePullPolicy: IfNotPresent
        name: melonvote-front
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-02-04T23:07:12Z"
    lastUpdateTime: "2022-02-04T23:07:12Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2022-02-04T23:07:12Z"
    lastUpdateTime: "2022-02-04T23:07:12Z"
    message: ReplicaSet "melonvote-front-8597dcd99" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
