apiVersion: v1
kind: Pod
metadata:
  name: configmap-multi-env-pod
spec:
  containers:
  - name: configmap-container
    image: busybox
    command: ["/bin/sh", "-c", "echo $(partner-server-location)"]
    env:
    - name: partner-server-location
      valueFrom:  
        configMapKeyRef:
          name: singlevalue-map
          key: partner-url