AWSTemplateFormatVersion: 2010-09-09
Description: My first template in this course.

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-001089eb624938d9f
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: My first instance

  WebServerSecurityGroup:
    Type:  AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for Web server
      GroupName: WebServerSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Web server security group

  MySQS:
    Type: AWS::SQS::Queue
    DependsOn: WebServerInstance
