apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: secret-containers
    image: busybox
    command: ['/bin/sh', '-c', 'env']
    envFrom:
    - secretRef:
        name: test-secret
