apiVersion: v1
kind: Pod
metadata: 
  name: command-pod
spec:
  containers:
  - name: container-with-command
    image: ubuntu #ubuntu:14.04
    command:
    - /bin/bash
    - -ec
    - while :; do echo '.'; sleep 1; done
    