# i never implemented this.  
# error (too common), even though I copied it directly from the text
# skip for now

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'root'
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subpath: mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessMode: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
