AWSTemplateFormatVersion: 2010-09-09
Description: Sample database stack for the Parameters section

Parameters:
  DBClass:
    Type: String
    Description: DB instance
    Default: db.t2.micro
    AllowedValues:
      - db.t2.micro
      - db.t2.small
  MasterUsername:
    Type: String
    Description: Master username for the database
    MaxLength: 10
    Default: dbadmin
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9]*'
    NoEcho: true
  MasterUserPassword:
    Type: String
    Description: Master username password
    MinLength: 8
    NoEcho: true
  MultiAZ:
    Type: String
    Description: Enable Multi-AZ?
    Default: false
    AllowedValues:
      - true
      - false
    ConstraintDescription: Value must be true or false.
  AllocatedStorage:
    Type: Number
    Description: Database size in GB
    MinValue: 8
    MaxValue: 16
    Default: 10
    ConstraintDescription: Min = 8 Max = 16
  SecurityGroupPorts:
    Type: List<Number>
    Description: 'Port numbers as a list: <web-server-port>,<database-port>'
    Default: '80,3306'
  DbSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'Db subnet ids as a list: <subnet1>,<subnet2>,....'
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: 'Webserver instances security group'
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort:
            Fn::Select: [0, !Ref SecurityGroupPorts]
          ToPort: !Select [0, !Ref SecurityGroupPorts]
          IpProtocol: tcp

  # Note: Please replace the value of VpcId property
  # with the VPC id of your default VPC
  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: 'Database instances security group'
      SecurityGroupIngress:
        - 
          CidrIp: 0.0.0.0/0
          FromPort: !Select [1, !Ref SecurityGroupPorts]
          ToPort: !Select [1, !Ref SecurityGroupPorts]
          IpProtocol: tcp

  # Note: Please replace the value of SubnetIds property 
  # with the subnet ids of the subnets in your default VPC!
  DbSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnets to launch db instances into
      SubnetIds: !Ref DbSubnets
#        - !Select [0, !Ref DbSubnets]
#        - !Select [1, !Ref DbSubnets]
#        - !Select [2, !Ref DbSubnets]

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: !Ref DBClass
      Engine: mariadb
      MultiAZ: !Ref MultiAZ
      PubliclyAccessible: true
      AllocatedStorage: !Ref AllocatedStorage
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName: !Ref DbSubnetGroup
      VPCSecurityGroups: 
        - !Ref DbSecurityGroup
      