apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  labels:
    app: chapter-activity  
spec:
  type: ClusterIP 
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: chapter-activity
    env: prod
    tier: backend
    