# details found at:  https://hub.docker.com/_/wordpress

version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - db_data:/var/lib/postgresql/data/ 

  web:
    image: packtworkshops/the-docker-workshop:chapter5-pta-web
    depends_on:
      - db
    volumes:
      - static_data:/service/static 

  nginx:
    image: packtworkshops/the-docker-workshop:chapter5-pta-nginx
    depends_on: 
      - web
    ports:
      - 8000:80
    volumes:
      - static_data:/service/static

volumes:
  static_data:
  db_data: