AWSTemplateFormatVersion: 2010-09-09

Description: First template 

Resources: 
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0ed9277fb7eb570c9 # N. Virginia
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref WebServerSecurityGroup
      Tags: 
        - Key: Name 
          Value: Web Server
        - Key: Project
          Value: CloudFormation Step by Step
  WebServerSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription:  SG for web servers 
      GroupName: WS-SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name 
          Value: Web server security group 
  SQSQueue:
    Type: AWS::SQS::Queue
    DependsOn: WebServerInstance