---
- name: install start and enable httpd
  hosts: exer
  tasks:
  - name: install package
    yum:
      name: httpd
      state: latest
  - service:
      name: httpd
      state: started
      enabled: yes
