apiVersion: v1
kind: Pod
metadata:
  name: infra-libraries-application
  namespace: ch06
  labels:
    env: prod
    criticality: critical
  annotations:
    team: infra-libraries
    team-link: infra-libraries-link
spec:
  containers:
  - name: infra-libraries-application
    image: nginx
    