apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
  labels:
    app: chapter-activity  
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: chapter-activity
    env: prod
    tier: frontend
    