---
- name: install and start the vdftpd service
  hosts: exercises
  tasks:
  - name: install vdftp
    yum:
      name: vsftpd
      state: latest
  - name: start and enable the vsftpd service
    service:
      name: vsftpd
      state: started
      enabled: yes
